### ISSUE TITLE
--- vs 1RZ

### ISSUE THREAD

**Issue by tyilo** [bbchallenge/bbchallenge#17]
On the story page both `---` and `1RZ` seems to be used for the 5-state record holder's `(0, E)` transition.

It doesn't look like it is described what `1RZ` actually means as `Z` is an invalid state.

Should all `..Z` transitions be changed to `---` for consistency?

Or is there a subtle difference?

**Comment by tyilo** [comment]
It also seems that `Copy code for https://turingmachine.io/` produces invalid code when using the `1RZ` transition.

With `---` (https://bbchallenge.org/1RB1LC_1RC1RB_1RD0LE_1LA1LD_---0LA):
```
blank: '0'
start state: A
table:
  A:
    0: {write: 1, R: B}
    1: {write: 1, L: C}
  B:
    0: {write: 1, R: C}
    1: {write: 1, R: B}
  C:
    0: {write: 1, R: D}
    1: {write: 0, L: E}
  D:
    0: {write: 1, L: A}
    1: {write: 1, L: D}
  E:
    1: {write: 0, L: A}
```

With `1RZ` (https://bbchallenge.org/1RB1LC_1RC1RB_1RD0LE_1LA1LD_1RZ0LA):
```
blank: '0'
start state: A
table:
  A:
    0: {write: 1, R: B}
    1: {write: 1, L: C}
  B:
    0: {write: 1, R: C}
    1: {write: 1, R: B}
  C:
    0: {write: 1, R: D}
    1: {write: 0, L: E}
  D:
    0: {write: 1, L: A}
    1: {write: 1, L: D}
  E:
    0: {write: 1, R: Z}
    1: {write: 0, L: A}
```

Error:
```
Undeclared state Z in the transition from state E and symbol 0.
Make sure to list all states in the transition table and define their transitions (if any).
```

**Comment by tcosmo** [comment]
> On the story page both `---` and `1RZ` seems to be used for the 5-state record holder's `(0, E)` transition.
> 
> It doesn't look like it is described what `1RZ` actually means as `Z` is an invalid state.
> 
> Should all `..Z` transitions be changed to `---` for consistency?
> 
> Or is there a subtle difference?

Hello @tyilo, thank you very much for reaching out !

So, there is a subtle difference indeed : we use `---` when we mean "we do not know if the transition can be reached" OR "we know the transition cannot be reached". Whereas, for a halting machine, such as the 5-state record holder, we actually do know that the transition is reached, since the machine halts. Note that the convention of a letter bigger than the number of states (such as Z or H) is historical and already used in [[Marxen & Buntrock, 1990]](https://turbotm.de/~heiner/BB/mabu90.html).

Although it is a good point that this is not discussed on the website, I think mainly not to weight the reader with too much details. It was discussed on the forum when we collectively chose a standard format for TMs allowing for both `---` and using a letter bigger than number of states : [https://discuss.bbchallenge.org/t/standard-tm-text-format/60/28](https://discuss.bbchallenge.org/t/standard-tm-text-format/60/28)


> It also seems that `Copy code for https://turingmachine.io/` produces invalid code when using the `1RZ` transition.
> 
> With `---` (https://bbchallenge.org/1RB1LC_1RC1RB_1RD0LE_1LA1LD_---0LA):
> 
> ```
> blank: '0'
> start state: A
> table:
>   A:
>     0: {write: 1, R: B}
>     1: {write: 1, L: C}
>   B:
>     0: {write: 1, R: C}
>     1: {write: 1, R: B}
>   C:
>     0: {write: 1, R: D}
>     1: {write: 0, L: E}
>   D:
>     0: {write: 1, L: A}
>     1: {write: 1, L: D}
>   E:
>     1: {write: 0, L: A}
> ```
> 
> With `1RZ` (https://bbchallenge.org/1RB1LC_1RC1RB_1RD0LE_1LA1LD_1RZ0LA):
> 
> ```
> blank: '0'
> start state: A
> table:
>   A:
>     0: {write: 1, R: B}
>     1: {write: 1, L: C}
>   B:
>     0: {write: 1, R: C}
>     1: {write: 1, R: B}
>   C:
>     0: {write: 1, R: D}
>     1: {write: 0, L: E}
>   D:
>     0: {write: 1, L: A}
>     1: {write: 1, L: D}
>   E:
>     0: {write: 1, R: Z}
>     1: {write: 0, L: A}
> ```
> 
> Error:
> 
> ```
> Undeclared state Z in the transition from state E and symbol 0.
> Make sure to list all states in the transition table and define their transitions (if any).
> ```

Good point ! 

That should be an easy fix in the conversion code, let's leave this issue open to fix that.

Thank you !

**Comment by tyilo** [comment]
> Although it is a good point that this is not discussed on the website, I think mainly not to weight the reader with too much details. It was discussed on the forum when we collectively chose a standard format for TMs allowing for both --- and using a letter bigger than number of states : https://discuss.bbchallenge.org/t/standard-tm-text-format/60/28

I think you could just change:
> The machine will halt (i.e. cease functionning) if it ever tries to execute an undefined transition denoted by ---.

to:
> The machine will halt (i.e. cease functioning) if it ever tries to execute an undefined transition denoted by --- or tries to transition to the special halt state called Z.

<hr>

There is still some inaccuracies in the story document:

> The conjecture is based on earlier work [[Marxen and Buntrock, 1990]](http://turbotm.de/~heiner/BB/mabu90.html) which discovered the current [5-state busy beaver champion](https://bbchallenge.org/1RB1LC_1RC1RB_1RD0LE_1LA1LD_1RZ0LA&w=250&ox=0.8&status=halt), a machine with 5 states that halts after 47,176,870 steps:
> https://bbchallenge.org/1RB1LC_1RC1RB_1RD0LE_1LA1LD_---0LA

If I understand correctly your definition of `---`, this TM will actually halt after 47,176,869 steps, not 47,176,870 steps.

**Comment by tcosmo** [comment]
> If I understand your definition of --- correctly, this TM will actually halt after 47,176,869 steps, not 47,176,870 steps.

Ahah, I do love this level of detail-orientdness. So here we have two conventions to reconcile, Marxen and Buntrock's `1RH` which does make an extra (useless as far as BB(n) (Rado's S function) is concerned) step at the end of the execution and ours with `---`. This is why I worded it  `if it ever tries to execute an undefined transition` with the underlying meaning that the step count does increment by 1 because the machine tried to exectute the transition.

Said otherwise the machine https://bbchallenge.org/1RB---_------ stops after **2 steps**, it needs the second step to realise its reached an undefined transition.

I am sure that you will agree this is just a matter of definition and that the main goal here is to be consistent with the `47,176,870` number which has been set in our minds by the historical literature.

**Comment by tcosmo** [comment]
> The machine will halt (i.e. cease functioning) if it ever tries to execute an undefined transition denoted by --- or tries to transition to the special halt state called Z.

The actual rule is more involved, is if it tries to transition to any state that is not defined by the machine. I personally don't think we should cloud the story with these details and trust the interested reader to find their answer here, on the forum or on our discord channel https://discord.com/invite/3uqtPJA9Uv (which your are welcome to join if you'd like !!). But I am open to changes if it is supported by others too, tagging some collaborators for their opinion @UncombedCoconut @sligocki and sending on discord for others.
